"""
Response Schemas — orchestrator/schemas/response.py
====================================================
Defines how agents send structured responses BACK to the Root Orchestrator.
"""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

# Import ToolCall from the sibling module so AgentResponse can reference it.
# try/except handles both package-import and direct-execution modes.
try:
    from .tool import ToolCall
except ImportError:
    from tool import ToolCall


# ============================================================================
# ENUMS
# ============================================================================

class ResponseStatus(str, Enum):
    """
    Enumeration of standard response statuses an agent can report.

    Values:
        SUCCESS              — Agent completed its task and has a final answer.
        FAILURE              — Agent encountered an unrecoverable error.
        NEEDS_TOOL_EXECUTION — Agent needs the orchestrator to execute one or
                               more tools before it can continue.
        PENDING              — Agent is still processing (used in async flows).
    """
    SUCCESS = "success"
    FAILURE = "failure"
    NEEDS_TOOL_EXECUTION = "needs_tool_execution"
    PENDING = "pending"


# ============================================================================
# MODELS
# ============================================================================

class AgentResponse(BaseModel):
    """
    Standardized schema for how agents report results back to the Root Orchestrator.

    Enables:
        • Returning final text answers (content).
        • Requesting tool execution from the orchestrator (tool_calls).
        • Reporting error states and latency metrics.
        • Attaching arbitrary debugging metadata.

    Data flow:
        Agent  --->  AgentResponse  --->  Root Orchestrator  --->  User / Next Agent
    """
    agent_id: str = Field(
        ...,
        description="Unique identifier or name of the agent submitting this response."
    )
    status: ResponseStatus = Field(
        default=ResponseStatus.SUCCESS,
        description="Status of the agent's output state."
    )
    content: Optional[str] = Field(
        default=None,
        description="Final natural language response generated by the agent for the user/orchestrator."
    )
    tool_calls: List[ToolCall] = Field(
        default_factory=list,
        description="List of tool calls requested by the agent if further execution is needed."
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if execution status is 'failure'."
    )
    execution_time_ms: Optional[float] = Field(
        default=None,
        description="Execution latency measurement in milliseconds."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional debugging or tracking data attached by the agent."
    )
