"""
Orchestrator Shared Schemas (Shared Tool-Calling Schema)
===================================================================
This module defines the standardized Pydantic data interface used for communication 
between Agents and the Root Orchestrator in the Riva-AGI system.
------------------------------------------
"""

import json
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ============================================================================
# 1. INPUT FORMAT SCHEMA
# ============================================================================

class InputType(str, Enum):
    """Supported input modalities for agent processing."""
    TEXT = "text"
    AUDIO = "audio"
    IMAGE = "image"
    MULTIMODAL = "multimodal"


class InputData(BaseModel):
    """
    Standardized schema for inputs sent to agents or orchestrator.
    
    Supports:
    - Multi-modal inputs: Text, Audio, and/or Image data.
    - Contextual metadata: Mood signals, user ID, session state, timestamps, etc.
    """
    input_type: InputType = Field(
        ...,
        description="Primary modality of the input payload (text, audio, image, multimodal)."
    )
    text_content: Optional[str] = Field(
        default=None,
        description="Text message, system prompt, or transcribed audio query."
    )
    audio_data: Optional[str] = Field(
        default=None,
        description="Audio payload: File path, web URL, or base64 encoded audio string."
    )
    image_data: Optional[str] = Field(
        default=None,
        description="Image payload: File path, web URL, or base64 encoded image string."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Flexible key-value map for contextual metadata (e.g., mood signals, user ID)."
    )


# ============================================================================
# 2. TOOL CALL STRUCTURE SCHEMA
# ============================================================================

class ToolCall(BaseModel):
    """
    Schema defining how an agent invokes an external tool.
    
    Must include:
    - tool_name: Identifies which tool/function to execute.
    - parameters: Dictionary containing arguments to pass into the tool function.
    - expected_return_type: Information on what output type the tool will return.
    """
    call_id: str = Field(
        ...,
        description="Unique identifier tracking this specific tool invocation request."
    )
    tool_name: str = Field(
        ...,
        description="Name of the tool function to call (e.g., 'web_search', 'calculate_sum')."
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value dictionary of arguments passed into the tool function."
    )
    expected_return_type: str = Field(
        ...,
        description="Expected data format returned by the tool (e.g., 'str', 'dict', 'image_url', 'json')."
    )


# ============================================================================
# 3. RESPONSE FORMAT SCHEMA
# ============================================================================

class ResponseStatus(str, Enum):
    """Enumeration of standard response statuses."""
    SUCCESS = "success"
    FAILURE = "failure"
    NEEDS_TOOL_EXECUTION = "needs_tool_execution"
    PENDING = "pending"


class AgentResponse(BaseModel):
    """
    Standardized schema for how agents report results back to the Root Orchestrator.
    
    Enables:
    - Returning final text answers.
    - Requesting tool execution from the root orchestrator.
    - Reporting error states and latency metrics.
    """
    agent_id: str = Field(
        ...,
        description="Unique identifier or name of the agent submitting this response."
    )
    status: ResponseStatus = Field(
        default=ResponseStatus.SUCCESS,
        description="Status of the agent's output state."
    )
    content: Optional[str] = Field(
        default=None,
        description="Final natural language response generated by the agent for the user/orchestrator."
    )
    tool_calls: List[ToolCall] = Field(
        default_factory=list,
        description="List of tool calls requested by the agent if further execution is needed."
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if execution status is 'failure'."
    )
    execution_time_ms: Optional[float] = Field(
        default=None,
        description="Execution latency measurement in milliseconds."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional debugging or tracking data attached by the agent."
    )


# ============================================================================
# 4. WORKING DUMMY EXAMPLE
# ============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print(" Riva-AGI: Shared Schema Verification Script")
    print("=" * 60)

    # Step 1: Simulate incoming multi-modal user input with mood metadata
    print("\n--- STEP 1: Creating InputData Instance ---")
    user_input = InputData(
        input_type=InputType.MULTIMODAL,
        text_content="Can you search for the latest weather in Tokyo and analyze this voice note?",
        audio_data="s3://riva-agi-bucket/audio/user_voice_123.wav",
        metadata={
            "user_id": "usr_98765",
            "mood_signals": {
                "sentiment": "curious",
                "urgency": "medium",
                "tone": "polite"
            },
            "session_id": "sess_abc_xyz"
        }
    )
    print(f"Input schema validated successfully!")
    print(f"Modality: {user_input.input_type}")
    print(f"User Query: {user_input.text_content}")
    print(f"Mood Sentiment Signal: {user_input.metadata['mood_signals']['sentiment']}")

    # Step 2: Simulate a Fake Agent deciding to make a Tool Call
    print("\n--- STEP 2: Fake Agent Creating a ToolCall Instance ---")
    fake_tool_call = ToolCall(
        call_id="call_weather_001",
        tool_name="get_current_weather",
        parameters={
            "location": "Tokyo, Japan",
            "units": "celsius"
        },
        expected_return_type="dict"
    )
    print(f"ToolCall schema created!")
    print(f"Tool Name: {fake_tool_call.tool_name}")
    print(f"Parameters: {fake_tool_call.parameters}")
    print(f"Expected Return: {fake_tool_call.expected_return_type}")

    # Step 3: Simulate Fake Agent packaging its response back to the Root Orchestrator
    print("\n--- STEP 3: Agent Response to Root Orchestrator ---")
    agent_response = AgentResponse(
        agent_id="agent_weather_orchestrator_v1",
        status=ResponseStatus.NEEDS_TOOL_EXECUTION,
        content="I need to fetch live weather data before answering your query.",
        tool_calls=[fake_tool_call],
        execution_time_ms=42.5,
        metadata={"model_used": "gemini-2.5-flash", "tokens_used": 150}
    )

    # Step 4: Serialize to JSON (How data is transmitted over networks/queues)
    print("\n--- STEP 4: Serialized JSON Response (Data Transmission Format) ---")
    json_output = agent_response.model_dump_json(indent=2)
    print(json_output)

    print("\n" + "=" * 60)
    print(" All schemas validated and working perfectly!")
    print("=" * 60)
