"""Chat data models for REST and streaming endpoints."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Payload for user chat requests."""
    message: str = Field(..., description="User message or instruction for Riva-AGI.")
    session_id: Optional[str] = Field(None, description="Optional multi-turn conversation session ID.")
    use_rag: Optional[bool] = Field(True, description="Whether to pre-fetch context from RAG knowledge base.")


class ChatResponse(BaseModel):
    """Structured response from the agent orchestration."""
    task_id: str = Field(..., description="Unique ID of the executed orchestration task.")
    agent_used: str = Field(..., description="Target agent that completed or handled the task.")
    intent: str = Field(..., description="Classified intent.")
    content: str = Field(..., description="Text content generated by the agent.")
    status: str = Field(..., description="Execution status: 'success' or 'failure'.")
    execution_time_ms: float = Field(0.0, description="Duration of task execution in milliseconds.")
    tool_calls: List[Dict[str, Any]] = Field(default_factory=list, description="Tool calls executed during run.")
    session_id: Optional[str] = Field(None, description="Session ID associated with this turn.")
